//go:build linux

package main

import (
	"bytes"
	"fmt"
	"net/netip"
	"os"
	"os/exec"
	"strings"

	"gowireguard/internal/proto"
)

func applyDNSConfig(iface string, cfg proto.DNSConfig) error {
	switch dnsApplyMode {
	case dnsModeOff:
		return fmt.Errorf("%w: dns push disabled (--dns-mode=off)", errDNSUnsupported)
	case dnsModeResolved:
		return applyResolvedDNS(iface, cfg)
	case dnsModeResolvConf:
		return applyResolvConfDNS(cfg)
	}

	// Auto: prefer systemd-resolved (split DNS, reverts with the link),
	// but only when it is actually answering — distros ship resolvectl
	// with resolved disabled, and a takeover of /etc/resolv.conf behind
	// a running resolved would fight its symlink management.
	if resolvedUsable() {
		return applyResolvedDNS(iface, cfg)
	}
	return applyResolvConfDNS(cfg)
}

func resolvedUsable() bool {
	resolvectl, err := exec.LookPath("resolvectl")
	if err != nil {
		return false
	}
	return exec.Command(resolvectl, "status").Run() == nil
}

func applyResolvedDNS(iface string, cfg proto.DNSConfig) error {
	resolvectl, err := exec.LookPath("resolvectl")
	if err != nil {
		return fmt.Errorf("%w: resolvectl not found; install/use systemd-resolved or set --dns-mode=resolv-conf", errDNSUnsupported)
	}

	if !cfg.Enabled {
		return runDNSCommand(resolvectl, "revert", iface)
	}

	if len(cfg.Nameservers) == 0 {
		return nil
	}

	args := append([]string{"dns", iface}, cfg.Nameservers...)
	if err := runDNSCommand(resolvectl, args...); err != nil {
		return err
	}

	domains := dnsResolvedDomains(cfg)
	if len(domains) > 0 {
		args = append([]string{"domain", iface}, domains...)
		if err := runDNSCommand(resolvectl, args...); err != nil {
			return err
		}
	}

	// Route only configured domains to the mesh DNS by default. Older
	// resolvectl versions may not support this verb; DNS still works
	// without it, so ignore failures here.
	_ = runDNSCommand(resolvectl, "default-route", iface, "false")

	return nil
}

func dnsResolvedDomains(cfg proto.DNSConfig) []string {
	seen := map[string]bool{}
	var out []string
	add := func(domain string) {
		if domain == "" || seen[domain] {
			return
		}
		seen[domain] = true
		out = append(out, domain)
	}

	for _, domain := range cfg.SearchDomains {
		add(domain)
		if cfg.MagicDNS {
			add("~" + domain)
		}
	}
	if cfg.MagicDNS && cfg.Domain != "" {
		add(cfg.Domain)
		add("~" + cfg.Domain)
	}

	return out
}

func runDNSCommand(name string, args ...string) error {
	out, err := exec.Command(name, args...).CombinedOutput()
	if err != nil {
		return fmt.Errorf("%s %v: %w: %s", name, args, err, out)
	}

	return nil
}

// --- /etc/resolv.conf fallback (hosts without systemd-resolved) ---
//
// Plain resolv.conf has no split-DNS concept, so the pushed nameservers
// become the host's resolvers for everything; the mesh DNS server must
// forward non-mesh names upstream. The original file content is kept
// beside it and restored when DNS push is disabled, on agent shutdown,
// and on the next startup after a crash.

var (
	resolvConfPath       = "/etc/resolv.conf"
	resolvConfBackupPath = "/etc/resolv.conf.wgmesh-orig"
)

const resolvConfMarker = "# Generated by wgmesh"

func applyResolvConfDNS(cfg proto.DNSConfig) error {
	if !cfg.Enabled {
		return restoreResolvConf()
	}

	if len(cfg.Nameservers) == 0 {
		return nil
	}

	// The server validates these, but a resolv.conf write splices
	// server-supplied strings into a security-sensitive file — reject
	// anything that isn't a bare IP / clean domain rather than trust.
	for _, ns := range cfg.Nameservers {
		if _, err := netip.ParseAddr(ns); err != nil {
			return fmt.Errorf("parse dns nameserver %q: %w", ns, err)
		}
	}
	domains := dnsPlainSearchDomains(cfg)
	for _, domain := range domains {
		if strings.ContainsAny(domain, " \t\n\r") {
			return fmt.Errorf("invalid dns search domain %q", domain)
		}
	}

	current, err := os.ReadFile(resolvConfPath)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("read %s: %w", resolvConfPath, err)
	}

	// Snapshot whatever is live right now unless it is already ours, so
	// repeated applies never overwrite the real original with our own
	// generated file.
	if !bytes.HasPrefix(current, []byte(resolvConfMarker)) {
		if err := os.WriteFile(resolvConfBackupPath, current, 0o644); err != nil {
			return fmt.Errorf("back up %s: %w", resolvConfPath, err)
		}
	}

	var b strings.Builder
	fmt.Fprintf(&b, "%s (dns push); do not edit.\n", resolvConfMarker)
	fmt.Fprintf(&b, "# Original saved at %s; restored when dns push is disabled or the agent exits.\n", resolvConfBackupPath)
	for _, ns := range cfg.Nameservers {
		fmt.Fprintf(&b, "nameserver %s\n", ns)
	}
	if len(domains) > 0 {
		fmt.Fprintf(&b, "search %s\n", strings.Join(domains, " "))
	}

	return writeResolvConf([]byte(b.String()))
}

func dnsPlainSearchDomains(cfg proto.DNSConfig) []string {
	seen := map[string]bool{}
	var out []string
	add := func(domain string) {
		if domain == "" || seen[domain] {
			return
		}
		seen[domain] = true
		out = append(out, domain)
	}

	for _, domain := range cfg.SearchDomains {
		add(domain)
	}
	if cfg.MagicDNS {
		add(cfg.Domain)
	}

	return out
}

// restoreResolvConf undoes a resolv.conf takeover if one is in effect:
// the current file carries our marker and the saved original is put
// back. Foreign content (rewritten by DHCP, an admin, or never touched)
// is left alone. Safe to call unconditionally; used on disable, on
// shutdown, and at startup to clean up after a crash.
func restoreResolvConf() error {
	if dnsApplyMode == dnsModeResolved || dnsApplyMode == dnsModeOff {
		return nil
	}

	current, err := os.ReadFile(resolvConfPath)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("read %s: %w", resolvConfPath, err)
	}
	if !bytes.HasPrefix(current, []byte(resolvConfMarker)) {
		// Something else owns the file now; a leftover backup is stale.
		_ = os.Remove(resolvConfBackupPath)
		return nil
	}

	backup, err := os.ReadFile(resolvConfBackupPath)
	if os.IsNotExist(err) {
		return fmt.Errorf("%s is wgmesh-managed but backup %s is missing; restore it manually", resolvConfPath, resolvConfBackupPath)
	}
	if err != nil {
		return fmt.Errorf("read %s: %w", resolvConfBackupPath, err)
	}

	if err := writeResolvConf(backup); err != nil {
		return err
	}

	return os.Remove(resolvConfBackupPath)
}

// writeResolvConf replaces resolv.conf with our content. Remove-first
// converts a symlinked resolv.conf into a plain file we own; inside
// containers the file is usually a bind mount that cannot be unlinked
// (EBUSY), so fall back to truncating in place.
func writeResolvConf(content []byte) error {
	_ = os.Remove(resolvConfPath)

	f, err := os.OpenFile(resolvConfPath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o644)
	if err != nil {
		return fmt.Errorf("open %s: %w", resolvConfPath, err)
	}
	if _, err := f.Write(content); err != nil {
		f.Close()
		return fmt.Errorf("write %s: %w", resolvConfPath, err)
	}

	return f.Close()
}
