package main

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"net"
	"net/http"
	"strconv"
	"strings"

	"golang.zx2c4.com/wireguard/wgctrl/wgtypes"

	"gowireguard/internal/psk"
	"gowireguard/internal/store"
)

type createMobilePeerRequest struct {
	Name             string `json:"name,omitempty"`
	PublicKey        string `json:"public_key,omitempty"`
	PrivateKey       string `json:"private_key,omitempty"`
	GatewayPublicKey string `json:"gateway_public_key"`
	GatewayEndpoint  string `json:"gateway_endpoint"`
}

type mobilePeerResponse struct {
	Peer         peerJSON `json:"peer"`
	Config       string   `json:"config"`
	PrivateKey   string   `json:"private_key,omitempty"`
	PresharedKey string   `json:"preshared_key"`
	Warnings     []string `json:"warnings,omitempty"`
}

func (s *server) handleCreateMobilePeer(w http.ResponseWriter, r *http.Request) {
	var req createMobilePeerRequest
	if !decodeJSON(w, r, 64<<10, &req) {
		return
	}

	privateKey, publicKey, generated, ok := parseMobileKeys(w, req.PrivateKey, req.PublicKey)
	if !ok {
		return
	}

	req.GatewayPublicKey = strings.TrimSpace(req.GatewayPublicKey)
	if _, err := wgtypes.ParseKey(req.GatewayPublicKey); err != nil {
		writeError(w, http.StatusBadRequest, "gateway_public_key must be a WireGuard public key")
		return
	}
	if err := validateMobileEndpoint(req.GatewayEndpoint); err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}

	gateway, ok, err := s.activePeerByPublicKey(r.Context(), req.GatewayPublicKey)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "internal error")
		return
	}
	if !ok {
		writeError(w, http.StatusBadRequest, "gateway_public_key must match an active peer")
		return
	}

	peer, err := s.store.CreateStaticPeer(r.Context(), publicKey, req.Name)
	switch {
	case errors.Is(err, store.ErrPeerExists):
		writeError(w, http.StatusConflict, err.Error())
		return
	case err != nil:
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}

	pairKey, err := psk.DerivePairKey(s.pskMaster, publicKey, gateway.PublicKey)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "internal error")
		return
	}
	dnsCfg, err := s.store.CurrentDNSConfig(r.Context())
	if err != nil {
		writeError(w, http.StatusInternalServerError, "internal error")
		return
	}

	cfg := s.mobileWireGuardConfig(peer, privateKey.String(), gateway.PublicKey, pairKey.String(), req.GatewayEndpoint, dnsCfg)
	warnings := []string{
		"Mobile/static WireGuard peers cannot use wgmesh WebSocket relay or live signal sync; the selected gateway endpoint must be reachable over UDP.",
	}
	if generated {
		warnings = append(warnings, "The private key was generated by the control plane and is returned only in this response; save/import this config now.")
	}
	if !s.store.DefaultAllow {
		warnings = append(warnings, "Your ACL default policy is deny; add an ACL rule that allows this mobile peer to the gateway/services it should reach.")
	}

	s.audit(r, "mobile_peer_create", http.StatusOK,
		fmt.Sprintf("peer id=%d gateway_peer=%d endpoint=%s", peer.ID, gateway.ID, req.GatewayEndpoint))
	s.signalSync("mobile_peer_create")

	writeJSON(w, http.StatusOK, mobilePeerResponse{
		Peer:         peerInfoJSON(peer),
		Config:       cfg,
		PrivateKey:   privateKey.String(),
		PresharedKey: pairKey.String(),
		Warnings:     warnings,
	})
}

func parseMobileKeys(w http.ResponseWriter, rawPrivate, rawPublic string) (wgtypes.Key, string, bool, bool) {
	rawPrivate = strings.TrimSpace(rawPrivate)
	rawPublic = strings.TrimSpace(rawPublic)

	switch {
	case rawPrivate == "" && rawPublic == "":
		key, err := wgtypes.GeneratePrivateKey()
		if err != nil {
			writeError(w, http.StatusInternalServerError, "internal error")
			return wgtypes.Key{}, "", false, false
		}
		return key, key.PublicKey().String(), true, true
	case rawPrivate == "":
		if _, err := wgtypes.ParseKey(rawPublic); err != nil {
			writeError(w, http.StatusBadRequest, "public_key must be a WireGuard public key")
			return wgtypes.Key{}, "", false, false
		}
		writeError(w, http.StatusBadRequest, "private_key is required when public_key is supplied so an importable mobile config can be returned")
		return wgtypes.Key{}, "", false, false
	default:
		key, err := wgtypes.ParseKey(rawPrivate)
		if err != nil {
			writeError(w, http.StatusBadRequest, "private_key must be a WireGuard private key")
			return wgtypes.Key{}, "", false, false
		}
		derived := key.PublicKey().String()
		if rawPublic != "" && rawPublic != derived {
			writeError(w, http.StatusBadRequest, "public_key does not match private_key")
			return wgtypes.Key{}, "", false, false
		}
		return key, derived, false, true
	}
}

func validateMobileEndpoint(endpoint string) error {
	endpoint = strings.TrimSpace(endpoint)
	if endpoint == "" {
		return fmt.Errorf("gateway_endpoint is required")
	}

	host, portRaw, err := net.SplitHostPort(endpoint)
	if err != nil {
		return fmt.Errorf("gateway_endpoint must be host:port, with IPv6 hosts in brackets")
	}
	if strings.TrimSpace(host) == "" {
		return fmt.Errorf("gateway_endpoint host is required")
	}
	port, err := strconv.Atoi(portRaw)
	if err != nil || port < 1 || port > 65535 {
		return fmt.Errorf("gateway_endpoint port must be between 1 and 65535")
	}

	return nil
}

func (s *server) activePeerByPublicKey(ctx context.Context, publicKey string) (store.PeerInfo, bool, error) {
	peers, err := s.store.ListPeers(ctx)
	if err != nil {
		return store.PeerInfo{}, false, err
	}

	for _, peer := range peers {
		if peer.PublicKey == publicKey && peer.RevokedAt == "" {
			return peer, true, nil
		}
	}

	return store.PeerInfo{}, false, nil
}

func (s *server) mobileWireGuardConfig(peer store.PeerInfo, privateKey, gatewayPublicKey, pairPSK, endpoint string, dnsCfg store.DNSConfig) string {
	var b bytes.Buffer
	fmt.Fprintln(&b, "[Interface]")
	fmt.Fprintf(&b, "PrivateKey = %s\n", privateKey)
	addresses := []string{peer.AssignedIP + "/32"}
	if peer.AssignedIP6 != "" {
		addresses = append(addresses, peer.AssignedIP6+"/128")
	}
	fmt.Fprintf(&b, "Address = %s\n", strings.Join(addresses, ", "))
	if dnsCfg.Enabled && len(dnsCfg.Nameservers) > 0 {
		fmt.Fprintf(&b, "DNS = %s\n", strings.Join(dnsCfg.Nameservers, ", "))
	}
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "[Peer]")
	fmt.Fprintf(&b, "PublicKey = %s\n", gatewayPublicKey)
	fmt.Fprintf(&b, "PresharedKey = %s\n", pairPSK)
	fmt.Fprintf(&b, "Endpoint = %s\n", strings.TrimSpace(endpoint))
	allowed := []string{s.currentNetworkConfig().NetworkCIDR}
	if network6 := s.currentNetworkConfig().NetworkCIDR6; network6 != "" {
		allowed = append(allowed, network6)
	}
	fmt.Fprintf(&b, "AllowedIPs = %s\n", strings.Join(allowed, ", "))
	fmt.Fprintf(&b, "PersistentKeepalive = %d\n", keepaliveSeconds)

	return b.String()
}
